### ISSUE TITLE
Cannot Build boost from source with this.

### ISSUE THREAD

**Issue by jdb130496** [Data-Oriented-House/PortableBuildTools#24]
Downloaded boost source from https://www.boost.org/users/download/ (Windows 7z file). bootstrap.bat on cmd console fails to locate vswhere and ultimately, vcvarsall.bat (as shown below) because components like Common7, Auxiliary etc. are not included in this build. I had to install VS Build Tools which seamlessly built boost starting with bootstrap.bat (boost) which created b2.exe (boost) and then simply running b2 created all libraries in stage folder in boost. 

Following is the extract from a successful bootstrap in cmd when VS build Tools were installed with selected components like VC and Windows Kits:

D:\Downloads\boost_1_86_0>.\bootstrap.bat
Building Boost.Build engine
LOCALAPPDATA=C:\Users\j1304\AppData\Local
Found with vswhere d:\Programs\vsbt
Found with vswhere d:\Programs\vsbt
Call_If_Exists "d:\Programs\vsbt\Common7\Tools\..\..\VC\Auxiliary\Build\vcvarsall.bat"  AMD64
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.11.1
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
###
### Using 'vc143' toolset.
###

**Comment by munohikari** [comment]
Good.

**Comment by jdb130496** [comment]
Did not understand the closing of issue. What I meant was, will it not be possible to include Auxillary and other folders required as a part of portable build, may be upcoming versions?

**Comment by munohikari** [comment]
No. Boost expects you to have original Build Tools from Microsoft, including vswhere and vcvarsall. And it includes them specifically because it's so hard to setup the environment.
This project uses a single batch file instead, which instantly sets up the environment strings. If i were to re-create the stupid Microsoft eco-system, i would just be re-creating original Build Tools, what's the point of that? Clearly, Boost people *expect* you to use the original Build Tools - so do that. This project is not for you, it's for people who don't build Boost in the first place.

**Comment by jdb130496** [comment]
Grateful for educating me. I am still learning the ropes.

**Comment by star-hengxing** [comment]
boost >= 1.85 provide cmake source tarball, We can remove b2 build system!
https://github.com/boostorg/boost/releases/download/boost-1.85.0/boost-1.85.0-cmake.tar.gz
